[package]
name = "dox-excel"
version = "0.1.0"
edition = "2021"
license = "MIT"
repository = "https://github.com/pyhub-apps/dox"

[lib]
path = "src/lib.rs"

[dependencies]
dox-core = { path = "../dox-core" }
calamine = "0.26"
rust_xlsxwriter = "0.78"
anyhow = "1.0"
tracing = "0.1"
